# Generated by Codex on 2026-05-19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alunos', '0005_aluno_curso_aluno_disciplinas_aluno_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aluno',
            name='matricula',
            field=models.CharField(blank=True, max_length=10, unique=True),
        ),
    ]
