# Generated by Codex on 2026-05-22

import re

from django.db import migrations, models
from django.utils import timezone


def converter_matriculas_antigas(apps, schema_editor):
    Aluno = apps.get_model('alunos', 'Aluno')
    base = f'ALU{timezone.localdate().year}'
    legacy_pattern = re.compile(r'^A(\d{3})$')
    novo_pattern = re.compile(rf'^{base}(\d{{4}})$')

    matriculas = Aluno.objects.values_list('matricula', flat=True)
    sequencias_usadas = set()

    for matricula in matriculas:
        resultado = novo_pattern.match(matricula or '')
        if resultado:
            sequencias_usadas.add(int(resultado.group(1)))

    proxima_sequencia = 1

    def gerar_matricula(preferida):
        nonlocal proxima_sequencia

        if preferida > 0 and preferida not in sequencias_usadas:
            sequencia = preferida
        else:
            while proxima_sequencia in sequencias_usadas:
                proxima_sequencia += 1
            sequencia = proxima_sequencia

        sequencias_usadas.add(sequencia)
        return f'{base}{sequencia:04d}'

    for aluno in Aluno.objects.order_by('id'):
        resultado = legacy_pattern.match(aluno.matricula or '')
        if not resultado:
            continue

        aluno.matricula = gerar_matricula(int(resultado.group(1)))
        aluno.save(update_fields=['matricula'])


def manter_matriculas_convertidas(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('alunos', '0006_alter_aluno_matricula'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aluno',
            name='matricula',
            field=models.CharField(blank=True, max_length=20, unique=True),
        ),
        migrations.RunPython(
            converter_matriculas_antigas,
            manter_matriculas_convertidas,
        ),
    ]
