# Generated by Django 6.0.5 on 2026-06-12 03:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alunos', '0007_alter_aluno_matricula_padrao'),
    ]

    operations = [
        migrations.AddField(
            model_name='aluno',
            name='turno',
            field=models.CharField(blank=True, choices=[('manha', 'Manhã'), ('tarde', 'Tarde'), ('noite', 'Noite')], default='', max_length=10),
        ),
    ]
