# Generated by Django 6.0.5 on 2026-06-12 03:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_profile_curso_profile_disciplinas'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='turno',
            field=models.CharField(blank=True, choices=[('manha', 'Manhã'), ('tarde', 'Tarde'), ('noite', 'Noite')], default='', max_length=10),
        ),
    ]
