# Generated by Django 6.0.5 on 2026-05-27 00:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('disciplinas', '0003_alter_disciplina_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cronograma',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dia_semana', models.CharField(choices=[('SEG', 'Segunda'), ('TER', 'TERÇA'), ('QUA', 'Quarta'), ('QUI', 'Quinta'), ('SEX', 'Sexta')], max_length=3)),
                ('horario_inicio', models.TimeField()),
                ('horario_fim', models.TimeField()),
                ('sala', models.CharField(max_length=50)),
                ('disciplina', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='disciplinas.disciplina')),
            ],
        ),
    ]
