# Generated by Django 6.0.5 on 2026-05-27 00:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cronograma', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cronograma',
            name='dia_semana',
            field=models.CharField(choices=[('SEG', 'Segunda'), ('TER', 'Terça'), ('QUA', 'Quarta'), ('QUI', 'Quinta'), ('SEX', 'Sexta')], max_length=3),
        ),
    ]
