# Generated by Django 6.0.5 on 2026-06-12 03:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cronograma', '0002_alter_cronograma_dia_semana'),
    ]

    operations = [
        migrations.AddField(
            model_name='cronograma',
            name='turno',
            field=models.CharField(choices=[('manha', 'Manhã'), ('tarde', 'Tarde'), ('noite', 'Noite')], default='noite', max_length=10),
        ),
    ]
