"""
Django settings for CRUD project.

Generated by 'django-admin startproject' using Django 6.0.5.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

import os
from pathlib import Path
from urllib.parse import parse_qsl, unquote, urlparse

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


def load_env_file(path):
    if not path.exists():
        return

    for raw_line in path.read_text().splitlines():
        line = raw_line.strip()
        if not line or line.startswith('#') or '=' not in line:
            continue

        key, value = line.split('=', 1)
        key = key.strip()
        value = value.strip().strip('\"').strip("'")
        os.environ.setdefault(key, value)


load_env_file(BASE_DIR / '.env')


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

def env_bool(name, default=False):
    return os.environ.get(name, str(default)).lower() in ('1', 'true', 'yes', 'on')


def env_int(name, default):
    value = os.environ.get(name)
    if value in (None, ''):
        return default
    return int(value)


PRODUCTION = env_bool('DJANGO_PRODUCTION', False)

# SECURITY WARNING: keep the secret key used in production secret.
SECRET_KEY = os.environ.get('DJANGO_SECRET_KEY')

if not SECRET_KEY:
    if PRODUCTION:
        raise RuntimeError('DJANGO_SECRET_KEY must be set when DJANGO_PRODUCTION=True.')
    SECRET_KEY = 'local-dev-secret-key-change-me-7Yd8qN2xQp4vR9mT6sL3cW5zA1bH0uK'

# SECURITY WARNING: don't run with debug turned on in production.
DEBUG = env_bool('DJANGO_DEBUG', not PRODUCTION)

default_allowed_hosts = 'localhost,127.0.0.1,[::1]' if not PRODUCTION else ''
ALLOWED_HOSTS = [
    host.strip()
    for host in os.environ.get('DJANGO_ALLOWED_HOSTS', default_allowed_hosts).split(',')
    if host.strip()
]

if PRODUCTION and not ALLOWED_HOSTS:
    raise RuntimeError('DJANGO_ALLOWED_HOSTS must be set when DJANGO_PRODUCTION=True.')


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'users.apps.UsersConfig',
    'alunos',
    'disciplinas',
    'notas', 
    'faltas',
    'cronograma',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'CRUD.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'users.context_processors.access_flags',
            ],
        },
    },
]

WSGI_APPLICATION = 'CRUD.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases


def database_config_from_url(database_url, *, require_ssl=False, supabase=False):
    parsed = urlparse(database_url)
    if parsed.scheme not in ('postgres', 'postgresql'):
        raise RuntimeError('A URL do banco deve começar com postgres:// ou postgresql://.')

    options = dict(parse_qsl(parsed.query, keep_blank_values=True))
    if require_ssl:
        options.setdefault('sslmode', 'require')

    config = {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': unquote(parsed.path.lstrip('/')),
        'USER': unquote(parsed.username or ''),
        'PASSWORD': unquote(parsed.password or ''),
        'HOST': parsed.hostname or '',
        'PORT': str(parsed.port or ''),
    }

    if options:
        config['OPTIONS'] = options

    missing = [
        key
        for key in ('NAME', 'USER', 'PASSWORD', 'HOST')
        if not config.get(key)
    ]
    if missing:
        raise RuntimeError(
            'A URL do banco esta incompleta. Campos ausentes: '
            + ', '.join(missing)
            + '.'
        )

    return apply_postgres_runtime_options(config, supabase=supabase)


def supabase_database_config_from_env():
    config = {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': os.environ.get('SUPABASE_DB_NAME', 'postgres'),
        'USER': os.environ.get('SUPABASE_DB_USER', 'postgres'),
        'PASSWORD': os.environ.get('SUPABASE_DB_PASSWORD', ''),
        'HOST': os.environ.get('SUPABASE_DB_HOST', ''),
        'PORT': os.environ.get('SUPABASE_DB_PORT', '5432'),
        'OPTIONS': {
            'sslmode': os.environ.get('SUPABASE_DB_SSLMODE', 'require'),
        },
    }

    missing = [
        key
        for key in ('PASSWORD', 'HOST')
        if not config.get(key)
    ]
    if missing:
        raise RuntimeError(
            'Configuracao do Supabase incompleta. Defina: '
            + ', '.join(f'SUPABASE_DB_{key}' for key in missing)
            + '.'
        )

    return apply_postgres_runtime_options(config, supabase=True)


def apply_postgres_runtime_options(config, *, supabase=False):
    if supabase:
        config['CONN_MAX_AGE'] = env_int('SUPABASE_DB_CONN_MAX_AGE', 60)
        config['CONN_HEALTH_CHECKS'] = env_bool('SUPABASE_DB_CONN_HEALTH_CHECKS', True)

        if env_bool('SUPABASE_DB_DISABLE_SERVER_SIDE_CURSORS', False):
            config['DISABLE_SERVER_SIDE_CURSORS'] = True
    elif 'DJANGO_DB_CONN_MAX_AGE' in os.environ:
        config['CONN_MAX_AGE'] = env_int('DJANGO_DB_CONN_MAX_AGE', 0)

    return config


SUPABASE_DATABASE_URL = os.environ.get('SUPABASE_DATABASE_URL')
DATABASE_URL = os.environ.get('DATABASE_URL')
SUPABASE_DB_ENV_VARS = (
    'SUPABASE_DB_HOST',
    'SUPABASE_DB_PASSWORD',
    'SUPABASE_DB_USER',
    'SUPABASE_DB_NAME',
    'SUPABASE_DB_PORT',
)

if SUPABASE_DATABASE_URL:
    DATABASES = {
        'default': database_config_from_url(
            SUPABASE_DATABASE_URL,
            require_ssl=True,
            supabase=True,
        ),
    }
elif DATABASE_URL:
    DATABASES = {
        'default': database_config_from_url(DATABASE_URL),
    }
elif env_bool('USE_SUPABASE', False) or any(os.environ.get(name) for name in SUPABASE_DB_ENV_VARS):
    DATABASES = {
        'default': supabase_database_config_from_env(),
    }
else:
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.sqlite3',
            'NAME': BASE_DIR / 'db.sqlite3',
        }
    }


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'pt-br'

TIME_ZONE = 'America/Sao_Paulo'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = 'static/'

STATICFILES_DIRS = [
    BASE_DIR / 'static',
]

LOGIN_URL = 'home'
LOGIN_REDIRECT_URL = '/portal/'
LOGOUT_REDIRECT_URL = '/login/'

EMAIL_HOST = os.environ.get('DJANGO_EMAIL_HOST', 'localhost')
EMAIL_HOST_USER = os.environ.get('DJANGO_EMAIL_HOST_USER', '')
EMAIL_HOST_PASSWORD = os.environ.get('DJANGO_EMAIL_HOST_PASSWORD', '')
SMTP_EMAIL_CONFIGURED = all([
    EMAIL_HOST,
    EMAIL_HOST_USER,
    EMAIL_HOST_PASSWORD,
])
DEFAULT_EMAIL_BACKEND = (
    'django.core.mail.backends.smtp.EmailBackend'
    if PRODUCTION or SMTP_EMAIL_CONFIGURED
    else 'django.core.mail.backends.console.EmailBackend'
)
EMAIL_BACKEND = os.environ.get('DJANGO_EMAIL_BACKEND', DEFAULT_EMAIL_BACKEND)
EMAIL_PORT = int(os.environ.get(
    'DJANGO_EMAIL_PORT',
    587 if EMAIL_BACKEND.endswith('smtp.EmailBackend') else 25,
))
EMAIL_USE_TLS = env_bool(
    'DJANGO_EMAIL_USE_TLS',
    EMAIL_BACKEND.endswith('smtp.EmailBackend'),
)
DEFAULT_FROM_EMAIL = os.environ.get(
    'DJANGO_DEFAULT_FROM_EMAIL',
    EMAIL_HOST_USER or 'Portal Tech <no-reply@portaltech.com>',
)

SECURE_SSL_REDIRECT = env_bool('DJANGO_SECURE_SSL_REDIRECT', PRODUCTION)
SESSION_COOKIE_SECURE = env_bool('DJANGO_SESSION_COOKIE_SECURE', PRODUCTION)
CSRF_COOKIE_SECURE = env_bool('DJANGO_CSRF_COOKIE_SECURE', PRODUCTION)
SECURE_HSTS_SECONDS = int(os.environ.get('DJANGO_SECURE_HSTS_SECONDS', 31536000 if PRODUCTION else 0))
SECURE_HSTS_INCLUDE_SUBDOMAINS = env_bool('DJANGO_SECURE_HSTS_INCLUDE_SUBDOMAINS', PRODUCTION)
SECURE_HSTS_PRELOAD = env_bool('DJANGO_SECURE_HSTS_PRELOAD', PRODUCTION)
